# Site settings
title: Kaj Rietberg
email: kaj@kajrietberg.nl
description: "Front-end developer, mountainbike and football enthousiastic"
baseurl: ""
url: "https://kajrietberg.nl"
twitter_username: Kajrietberg
github_username:  kajrietberg

# Build settings
sass:
  sass_dir: _sass
sass:
    style: compressed
    #style: expanded
    #style: nested
    #style: compact

markdown: kramdown
permalink: /:year/:month/:title
#paginate: 10    