[build]
  publish = "dist"
  functions = "functions"
  command = "npm run build "


# Redirect a likely mistake
# [[redirects]]
#   from = "/posts/2013*"
#   to = "/2013*"
#   status = 302

# 404
#[[redirects]]
#   from = "/*"
#   to = "/404"
#   status = 404


