[build]
  publish = "dist"
  functions = "functions"
  command = "npm run build "

# sample dev block in the toml
# note: each of these fields are OPTIONAL and should only be used if you need an override
#[dev]
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # If you use a _redirect file, provide the path to your static content folder

# 404
[[redirects]]
   from = "/*"
   to = "/404"
   status = 404